language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet build
 - (cd ./Brthor.Http.Tests && dotnet test && cd ..)
after_success:
 - bash publish.sh
cache:
  directories:
  - $HOME/.nuget